### ISSUE TITLE
Buscadores

### ISSUE THREAD

**Issue by EzequielLuppino** [chrisgel15/gdd2017#4]
Según el enunciado debería haber un buscador por cada campo. Ej nombre, apellido, dni. Por ejemplo si se quiere buscar por nombre y apellido no se puede.

![imagen](https://cloud.githubusercontent.com/assets/22202366/26523851/7a2a755e-42f7-11e7-80c2-85547e5a6280.png)

**Comment by chrisgel15** [comment]
Hecho.
