### ISSUE TITLE
Choferes

### ISSUE THREAD

**Issue by EzequielLuppino** [chrisgel15/gdd2017#5]
Al momento de seleccionar un chofer, se deberá mostrar automáticamente el automóvil habilitado que el chofer tiene asignado en ese momento
![imagen](https://cloud.githubusercontent.com/assets/22202366/26611409/8c30543c-4584-11e7-90ec-cc522762de1c.png)

**Comment by chrisgel15** [comment]
Lo pedido corresponde al ABM de viajes, no al ABM de Choferes.

Saludos!
