### ISSUE TITLE
ABM Autos

### ISSUE THREAD

**Issue by luciagonzalezq** [chrisgel15/gdd2017#6]
![imagen](https://user-images.githubusercontent.com/22283965/27616391-e699cf18-5b85-11e7-8936-0dbfce9da4ee.png)

Al querer modificar un automóvil, donde tengo todos los turnos marcados, deselecciono uno, acepto y me tira este error.

**Comment by FedericoMandri** [comment]
@luciagonzalezq debería estar resuelto, porfa probalo de nuevo.

**Comment by luciagonzalezq** [comment]
Ahora si, me deja modificar los turnos 👍
